In [1]:
x = 1
typeof(x)

Int64

In [2]:
y = 1.0
typeof(y)

Float64

In [3]:
2*x
2x

2

In [4]:
-3.0 + 2.0*im

-3.0 + 2.0im

In [5]:
π

π = 3.1415926535897...

In [6]:
x = 1
x += 5

6

In [7]:
show(x)

6

In [8]:
x;

In [9]:
show([1 2])

[1 2]

In [10]:
println(x)

6


In [11]:
print("1")
println("2")
println("3")

12
3


In [12]:
@printf "The formatting of %5.3f is similar to the C language\n" pi

The formatting of 3.462 is similar to the C language


In [13]:
info("Everything is going well")
warn("I can see clouds on the horizon")
error("The storm is here")

INFO: Everything is going well


LoadError: The storm is here

In [14]:
a = [1.0 -1.0 1.0]

1×3 Array{Float64,2}:
 1.0  -1.0  1.0

In [15]:
a = [pi, 2pi, 3pi]

3-element Array{Float64,1}:
 3.14159
 6.28319
 9.42478

In [16]:
show(a)

[3.89159,6.28319,9.42478]

In [17]:
@show a

a = [3.14159,6.28319,9.42478]


3-element Array{Float64,1}:
 3.14159
 6.28319
 9.42478

In [18]:
a = [pi -1.0; 2.0 3.0]

2×2 Array{Float64,2}:
 3.14159  -1.0
 2.0       3.0

In [19]:
@show eye(2)
@show zeros(2,1)

eye(2) = [1.0 0.0; 0.0 1.0]
zeros(2,1) = [0.0; 0.0]


2×1 Array{Float64,2}:
 0.0
 0.0

In [20]:
x = [-1.0 3.0 5.0 pi]
@show x[1] x[2] x[end]

x[1] = -1.0
x[2] = 3.0
x[end] = 3.141592653589793


3.141592653589793

In [21]:
a = [pi -1.0; 2.0 3.0];
@show a[1,2]

a[1,2] = -1.0


-1.0

In [22]:
a[2,2] = e
@show a

a = [3.14159 -1.0; 2.0 2.71828]


2×2 Array{Float64,2}:
 3.14159  -1.0    
 2.0       2.71828

In [23]:
@show a[:,1]
@show a[2,:]

a[:,1] = [3.14159,2.0]
a[2,:] = [2.0,2.71828]


2-element Array{Float64,1}:
 2.0    
 2.71828

In [24]:
a = [-1 1]
b = a
@show a
b[1] = 15
@show a

a = [-1 1]
a = [15 1]


1×2 Array{Int64,2}:
 15  1

In [25]:
a = [-1 1]
b = copy(a)
@show a
b[1] = 15
@show a

a = [-1 1]
a = [-1 1]


1×2 Array{Int64,2}:
 -1  1

In [26]:
x = Vector{Float64}(2)
A = Matrix{Float64}(3,2)
@show x A

x = [6.45351e-314,2.20127e-314]
A = [2.25095e-314 2.25095e-314; 2.25095e-314 2.25107e-314; 2.25095e-314 2.25857e-314]


3×2 Array{Float64,2}:
 2.25095e-314  2.25095e-314
 2.25095e-314  2.25107e-314
 2.25095e-314  2.25857e-314

In [27]:
x = [ 1.0 / sqrt(1.0 + i^2) for i=1:4 ]
@show x
A = [ i-j^2 for i=1:4, j=1:2 ]
@show A

x = [0.707107,0.447214,0.316228,0.242536]
A = [0 -3; 1 -2; 2 -1; 3 0]


4×2 Array{Int64,2}:
 0  -3
 1  -2
 2  -1
 3   0

In [28]:
A = [1 0; -1 1]
x = [1, pi]
A*x

2-element Array{Float64,1}:
 1.0    
 2.14159

In [29]:
A = [1 0; 1 1]
x = [1, 0]
A \ x

2-element Array{Float64,1}:
  1.0
 -1.0

In [30]:
x = [1.0 2.0]
@show x.^2
y = [-1.0 5.0]
@show x .+ y
@show x .* y

x .^ 2 = [1.0 4.0]
x .+ y = [0.0 7.0]
x .* y = [-1.0 10.0]


1×2 Array{Float64,2}:
 -1.0  10.0

In [31]:
x = [1.0 2.0]
@show exp(x)

exp(x) = [2.71828 7.38906]


1×2 Array{Float64,2}:
 2.71828  7.38906

In [32]:
s = 0.0
for i=1:10
    s += 1.0 / i
end
s

2.9289682539682538

In [33]:
s = 0.0
for i = 0:2:8
    s += 1.0 / i
end

In [34]:
s = 0.0
for i = 2.^(0:2:8)
    s += 1.0 / i
end
2.^(0:2:8)

5-element Array{Int64,1}:
   1
   4
  16
  64
 256

In [35]:
s = 0.0
for i = [1 4 16]
    s += 1.0 / i
end
s

1.3125

In [36]:
x = 1.0; f = 1.0; i = 2
while f > eps(1.0)
    x += f
    f /= i
    i += 1
end
@show x,e

(x,e) = (2.7182818284590455,e = 2.7182818284590...)


(2.7182818284590455,e = 2.7182818284590...)

In [37]:
function flog(n,x)
    p = -x
    l = 0.0
    for i=1:n
        l += p/i
        p *= x
    end
    return l
end
@show flog(20,0.5), log(1-0.5)

(flog(20,0.5),log(1 - 0.5)) = (-0.6931471370510288,-0.6931471805599453)


(-0.6931471370510288,-0.6931471805599453)

In [38]:
fpower(x,y) = x^y
@show fpower(2,3)

fpower(2,3) = 8


8

In [39]:
map(x -> x^2 + 2x + 1, 1:4)

4-element Array{Int64,1}:
  4
  9
 16
 25

In [40]:
function f_reference(x,y)
    x += 1
    y[1] += 1
    return x
end
x = 1
y = [-4 3]
@show x,y
@show f_reference(x,y)
@show x,y

(x,y) = (1,
[-4 3])
f_reference(x,y) = 2
(x,y) = (1,
[-3 3])


(1,
[-3 3])

In [41]:
tup = (pi,e)
tup[1]

π = 3.1415926535897...

In [42]:
function f_multiple(x)
    return (x, 2x, 4x)
end
f_multiple(3)

(3,6,12)

In [43]:
x, y = golden, eulergamma
@show x, y

(x,y) = (φ = 1.6180339887498...,γ = 0.5772156649015...)


(φ = 1.6180339887498...,γ = 0.5772156649015...)

In [44]:
f_multiple.([1, 2])

2-element Array{Tuple{Int64,Int64,Int64},1}:
 (1,2,4)
 (2,4,8)

In [45]:
function f_type(x::UInt32) # 32 bit unsigned integer
    return x + 3
end
@show f_type(UInt32(1))
#f_type(UInt32(-1)) # Conversion error
#f_type(1)          # Wrong type for input variable; 1 is an Int64

f_type(UInt32(1)) = 4


4

In [46]:
function f_if_then_else(x)
    if x > 0
        return log(x)
    elseif x < 0
        warn("The input argument is negative; returning log(-x)")
        return log(-x)
    else
        error("The input argument is equal to 0")
    end
end
@show f_if_then_else(2)
@show f_if_then_else(-2)
@show f_if_then_else(0)

f_if_then_else(2) = 0.6931471805599453
f_if_then_else(-2) = 0.6931471805599453


LoadError: The input argument is equal to 0