In [1]:
# Initialize the random number generator
rng = MersenneTwister(17);

In [2]:
function pretty_print(v)
    @printf "["
    for i=1:length(v)
        @printf "%8.5f" v[i]
        if i < length(v)
            @printf "  "
        end
    end
    @printf "]\n"
end    

pretty_print (generic function with 1 method)

In [3]:
# Size of matrix
n = 3
X = rand(rng, n, n)
Λ = diagm(Float32[2.0^(-i) for i=0:n-1])

A = X * Λ / X

3x3 Array{Float64,2}:
  0.15695   0.198397  -0.0967046
 -1.20509   1.19549   -0.0111219
 -0.990164  0.571865   0.397559 

In [4]:
x1 = X[:,1]
x1 /= norm(x1)
# Largest e-value: 1
# E-vector: x1

qk = randn(rng, n)
qk /= norm(qk)

niter = 20
err = zeros(niter)

for k=1:niter
    zk = A * qk          # Power iteration: multiply by A
    eval = dot(zk,qk)    # E-value approximation
    qk = zk/norm(zk)     # Normalize e-vector

    if k < 8 # We stop printing afterwards
        @printf "Iteration: %2d | e-value: %7.4f | qk, x1 =\n" k eval
        pretty_print(qk)
        pretty_print(x1)
    end
    err[k] = abs(Λ[1,1] - eval)
end

Iteration:  1 | e-value:  0.6141 | qk, x1 =
[-0.15209  -0.94004  -0.30529]
[ 0.12703   0.81522   0.56505]
Iteration:  2 | e-value:  1.0636 | qk, x1 =
[-0.16724  -0.86662  -0.47011]
[ 0.12703   0.81522   0.56505]
Iteration:  3 | e-value:  0.9872 | qk, x1 =
[-0.15442  -0.83847  -0.52262]
[ 0.12703   0.81522   0.56505]
Iteration:  4 | e-value:  0.9805 | qk, x1 =
[-0.14278  -0.82632  -0.54481]
[ 0.12703   0.81522   0.56505]
Iteration:  5 | e-value:  0.9866 | qk, x1 =
[-0.13547  -0.82065  -0.55514]
[ 0.12703   0.81522   0.56505]
Iteration:  6 | e-value:  0.9923 | qk, x1 =
[-0.13139  -0.81791  -0.56015]
[ 0.12703   0.81522   0.56505]
Iteration:  7 | e-value:  0.9959 | qk, x1 =
[-0.12925  -0.81655  -0.56261]
[ 0.12703   0.81522   0.56505]


In [6]:
using Plots
plotlyjs()
# Error in eigenvalue calculation
# Semilogy plot
plot(err,yscale=:log10,left_margin=30mm)
xaxis!("Iteration")
yaxis!("Error")