In [1]:
include("geqrf.jl")

geqrfGS (generic function with 1 method)

In [2]:
n = 32
x = rand(n)

32-element Array{Float64,1}:
 0.415916 
 0.43767  
 0.329398 
 0.862195 
 0.597538 
 0.168616 
 0.0341336
 0.489089 
 0.593423 
 0.0748041
 0.834973 
 0.469812 
 0.795244 
 ⋮        
 0.507305 
 0.369299 
 0.856091 
 0.290203 
 0.742931 
 0.13874  
 0.0446816
 0.549649 
 0.197724 
 0.466844 
 0.431455 
 0.508584 

In [3]:
beta, v = house(x)

(0.8540547508025111,[1.0,-0.179823,-0.135338,-0.354245,-0.245507,-0.0692784,-0.0140243,-0.200949,-0.243816,-0.0307343  …  -0.351737,-0.119234,-0.305244,-0.0570035,-0.0183581,-0.225831,-0.0812378,-0.19181,-0.17727,-0.208959])

In [4]:
y = zeros(n); y[1] = norm(x)
Px = x - beta * dot(v,x) * v
@show norm(Px - y)

norm(Px - y) = 6.858632435964056e-16


6.858632435964056e-16

In [5]:
e1 = zeros(n); e1[1] = 1.0
e1'

1x32 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [6]:
# Insert Julia code for exercise here

In [7]:
# Testing QR factorization using Householder transformations
n = 4

# Building an orthogonal matrix Q
Q = zeros(n,n)
for j=0:n-1, i=0:n-1
    Q[i+1,j+1] = cos(π*(2i+1)*j/2n)
end
for j=1:n
    Q[:,j] /= norm(Q[:,j])
end

# Initializing an upper triangular matrix R
R = triu(Float64[ i/j for i=1:n, j=1:n ])

# Matrix A
A = Q*R
# QR factorization
geqrf!(A)
# The factor R is stored in the upper triangular part of A

# These matrices should match up to the sign of each row
@show R,triu(A)

(R,triu(A)) = (
[1.0 0.5 0.3333333333333333 0.25
 0.0 1.0 0.6666666666666666 0.5
 0.0 0.0 1.0 0.75
 0.0 0.0 0.0 1.0],

[1.0 0.5 0.33333333333333326 0.24999999999999967
 0.0 0.9999999999999999 0.6666666666666667 0.5000000000000002
 0.0 0.0 1.0 0.75
 0.0 0.0 0.0 -1.0000000000000004])


(
4x4 Array{Float64,2}:
 1.0  0.5  0.333333  0.25
 0.0  1.0  0.666667  0.5 
 0.0  0.0  1.0       0.75
 0.0  0.0  0.0       1.0 ,

4x4 Array{Float64,2}:
 1.0  0.5  0.333333   0.25
 0.0  1.0  0.666667   0.5 
 0.0  0.0  1.0        0.75
 0.0  0.0  0.0       -1.0 )