In [20]:
n = 100
println("Size of matrix ", n)

# Initialize the random number generator
rng = MersenneTwister()
srand(rng,2016);

Size of matrix 100


In [21]:
# Initialize the matrix
Qe, Re = qr(rand(n,n))
# Qe is orthogonal, Re is upper triangular
for i=1:n
    # Multiply row i by 1/2^i
    Re[i,:] /= 2.0^(i/3.2)
end

# A = Qe * Re
A = Qe * Re

100x100 Array{Float64,2}:
 0.232013   0.465931   0.302787   0.171239  …  0.304122   0.294825  0.346204
 0.423923   0.110158   0.118809   0.146936     0.231141   0.232082  0.192774
 0.563675   0.374586   0.365052   0.470234     0.429727   0.423167  0.418462
 0.742348   0.422258   0.392294   0.572932     0.465739   0.478383  0.519336
 0.354684   0.387623   0.378326   0.555012     0.322785   0.344664  0.435702
 0.729969   0.457436   0.509164   0.563351  …  0.506315   0.488468  0.512236
 0.439658   0.646943   0.455061   0.224522     0.420897   0.377645  0.442352
 0.190296   0.497899   0.564405   0.521545     0.318694   0.308501  0.450729
 0.599053   0.454904   0.393327   0.358556     0.457939   0.435148  0.460616
 0.672347   0.531917   0.702929   0.48234      0.550512   0.526382  0.514949
 0.389425   0.696006   0.36373    0.191647  …  0.435454   0.379395  0.415142
 0.313872   0.599609   0.311459   0.528617     0.374113   0.375363  0.488815
 0.382734   0.0684468  0.472275   0.170672     0.2

In [22]:
# Compute QR factorization of A
Q, R = qr(A)

# Fix possible differences in the sign of the diagonal entries of R
for i=1:n
    if R[i,i] * Re[i,i] < 0
        R[i,:] = -R[i,:]
        Q[:,i] = -Q[:,i]
    end
end

# We now expect that Q=Qe and R=Re.

In [23]:
# Calculate the error in Q
e = zeros(n)
for j=1:n
    # Processing column j
    e[j] = norm(Q[:,j] - Qe[:,j])
end

In [24]:
Q[end-2:end,end-2:end]

3x3 Array{Float64,2}:
 -0.033099    0.0890033   0.0745556
 -0.0778292  -0.178561   -0.0350562
  0.076302    0.0728049  -0.114085 

In [25]:
Qe[end-2:end,end-2:end]

3x3 Array{Float64,2}:
 -0.0330996   0.0890036   0.0745546
 -0.0778291  -0.178561   -0.0350574
  0.076303    0.0728046  -0.114084 

In [26]:
using Plots
plotly()

Plots.PlotlyBackend()

In [27]:
# Re-run all cells to get the plot below
plot(e, lab="Error in R[i,i]", yscale = :log, 
xlabel="Column index", ylabel="Error", left_margin = 50px)

In [32]:
using HDF5
h5open("QR_hwk_matrix_data.h5", "w") do file
    write(file,"matrix_A", A)
end

In [33]:
A0 = h5read("QR_hwk_matrix_data.h5", "matrix_A")
@show norm(A - A0)

norm(A - A0) = 0.0


0.0