In [2]:
include("geqrf.jl")

geqrfMGS! (generic function with 1 method)

In [3]:
n = 32
x = rand(n)

32-element Array{Float64,1}:
 0.236729  
 0.476513  
 0.589524  
 0.336845  
 0.5636    
 0.221532  
 0.821042  
 0.841374  
 0.615093  
 0.190004  
 0.842753  
 0.00322135
 0.709239  
 ⋮         
 0.576871  
 0.542172  
 0.832438  
 0.967977  
 0.961315  
 0.214749  
 0.519267  
 0.652337  
 0.0626117 
 0.729213  
 0.645761  
 0.425333  

In [4]:
beta, v = house(x)

(0.930169347639067,[1.0,-0.151115,-0.186954,-0.106823,-0.178733,-0.0702537,-0.260374,-0.266823,-0.195063,-0.0602554  …  -0.263988,-0.306972,-0.304859,-0.0681026,-0.164674,-0.206874,-0.0198559,-0.231253,-0.204788,-0.134885])

In [5]:
y = zeros(n); y[1] = norm(x)
Px = x - beta * dot(v,x) * v
@show norm(Px - y)

norm(Px - y) = 4.967009300928487e-16


4.967009300928487e-16

In [6]:
e1 = zeros(n); e1[1] = 1.0
e1'

1x32 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [7]:
# Insert Julia code for exercise here

In [8]:
# Testing QR factorization using Householder transformations
n = 4

# Building an orthogonal matrix Q
Q = zeros(n,n)
for j=0:n-1, i=0:n-1
    Q[i+1,j+1] = cos(π*(2i+1)*j/2n)
end
for j=1:n
    Q[:,j] /= norm(Q[:,j])
end

# Initializing an upper triangular matrix R
R = triu(Float64[ i/j for i=1:n, j=1:n ])

# Matrix A
A = Q*R
# QR factorization
geqrf!(A)
# The factor R is stored in the upper triangular part of A

# These matrices should match up to the sign of each row
@show R,triu(A)

(R,triu(A)) = (
[1.0 0.5 0.3333333333333333 0.25
 0.0 1.0 0.6666666666666666 0.5
 0.0 0.0 1.0 0.75
 0.0 0.0 0.0 1.0],

[1.0 0.5 0.33333333333333326 0.24999999999999967
 0.0 0.9999999999999999 0.6666666666666667 0.5000000000000002
 0.0 0.0 1.0 0.75
 0.0 0.0 0.0 -1.0000000000000004])


(
4x4 Array{Float64,2}:
 1.0  0.5  0.333333  0.25
 0.0  1.0  0.666667  0.5 
 0.0  0.0  1.0       0.75
 0.0  0.0  0.0       1.0 ,

4x4 Array{Float64,2}:
 1.0  0.5  0.333333   0.25
 0.0  1.0  0.666667   0.5 
 0.0  0.0  1.0        0.75
 0.0  0.0  0.0       -1.0 )

In [22]:
# Testing accuracy of QR factorizations using Householder transformations
n = 256

# Building an orthogonal matrix Q
Q = zeros(n,n)
for j=0:n-1, i=0:n-1
    Q[i+1,j+1] = cos(π*(2i+1)*j/2n)
end
for j=1:n
    Q[:,j] /= norm(Q[:,j])
end

# Initializing a random upper triangular matrix R
R = triu(rand(n,n))

# Matrix A
A = Q*R
A0 = copy(A)
# QR factorization
geqrf!(A)
# The factor R is stored in the upper triangular part of A

# Fixing the sign
for i=1:n
    if A[i,i] * R[i,i] < 0
        R[i,:] = -R[i,:]
        Q[:,i] = -Q[:,i]
    end
end

# Testing the accuracy of Q and R
@show norm(R - triu(A)) # Forward error
@show norm(Q*R - A0) # Backward error
@show norm(Q' * Q - eye(n,n)) # Orthogonality of Q

norm(R - triu(A)) = 66.33802856404111
norm(Q * R - A0) = 0.0
norm(Q' * Q - eye(n,n)) = 9.41588211381689e-14


9.41588211381689e-14