In [1]:
# Initialize the random number generator
rng = MersenneTwister(0);

In [2]:
# Size of the matrix
n = 512;

In [3]:
# Random initialization of matrix A
L = zeros(Float64,n,n)
U = zeros(Float64,n,n)
for i=1:n
    L[i,i] = 1
    L[i+1:n,i] = rand(rng, -2:2, n-i)
    U[i,i] = rand(rng, 1:2)
    U[i,i+1:n] = rand(rng, -2:2, n-i)
end
A = L * U
A0 = copy(A);
A0[1:6,1:6]

6×6 Array{Float64,2}:
  1.0  -1.0  -2.0   2.0   2.0  -2.0
 -2.0   4.0   4.0  -3.0  -6.0   2.0
 -1.0   5.0   4.0  -1.0  -4.0   0.0
  2.0  -4.0  -4.0   4.0   7.0  -2.0
  0.0  -4.0   2.0  -1.0  10.0   7.0
  2.0   2.0   0.0   3.0   7.0  -1.0

In [4]:
# Initializing the right-hand side
xe = rand(rng, 0:9, n) # This will be our solution
b = A * xe
b'

1×512 RowVector{Float64,Array{Float64,1}}:
 48.0  -188.0  -288.0  392.0  551.0  …  -2369.0  -2213.0  1989.0  -1777.0

In [5]:
include("../src/getrf.jl")

getrs (generic function with 3 methods)

In [6]:
# Test our solvers
map([getrfOuter!, getrfAxpy!, getrfDot!]) do solver
    A = copy(A0)
    solver(A)
    # Solve
    x = getrs(A, b)
    @assert x == xe
    println(string(solver) * ": PASSED")
end    

getrfOuter!: PASSED
getrfAxpy!: PASSED
getrfDot!: PASSED


3-element Array{Void,1}:
 nothing
 nothing
 nothing

In [7]:
# Time the solvers
map([getrfOuter!, getrfAxpy!, getrfDot!]) do solver
    A = copy(A0); @time solver(A)
end

  0.417327 seconds
  0.054532 seconds
  0.149087 seconds


3-element Array{Void,1}:
 nothing
 nothing
 nothing