In [1]:
using LinearAlgebra
using Random
rng = MersenneTwister();

In [2]:
Random.seed!(rng, 2018)

# Size of the matrix
n = 4;

# Initialization of matrix A
@show n
L = zeros(Float64,n,n)
U = zeros(Float64,n,n)
for i=1:n
    L[i,i] = 1
    U[i,i] = 1
    U[i,i+1:n] = rand(rng, 0:9, n-i)
end
L[3, [1,3,4]] = [1,0,1]
L[4,[3,4]] = [1,0]
display("L,U =")
display(L)
display(U)
A = L * U
@show det(A)
println("A:\n")
A

"L,U ="

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 1.0  0.0  0.0  1.0
 0.0  0.0  1.0  0.0

4×4 Array{Float64,2}:
 1.0  3.0  4.0  0.0
 0.0  1.0  3.0  1.0
 0.0  0.0  1.0  7.0
 0.0  0.0  0.0  1.0

n = 4
det(A) = -1.0
A:



4×4 Array{Float64,2}:
 1.0  3.0  4.0  0.0
 0.0  1.0  3.0  1.0
 1.0  3.0  4.0  1.0
 0.0  0.0  1.0  7.0

In [3]:
include("../src/getrf.jl")

getrs (generic function with 3 methods)

In [4]:
# This call is expected to fail
try
    getrfOuter!(A)
    println("The algorithm completed successfully.")
catch
    println("One of the pivots A[k,k] was 0. The algorithm could not proceed.")
end    

One of the pivots A[k,k] was 0. The algorithm could not proceed.


In [5]:
n = 2
ϵ = 1e-17
# ϵ = 1e-17 # Type \epsilon [TAB]
# ϵ = 64.0 * eps(Float64) / π 
# ϵ = eps(Float64) / π 
# ϵ = 0.25 * eps(Float64) / π
A = [ϵ 1; 1 π] # Type \pi [TAB]
A0 = copy(A)

getrfOuter!(A)
L = tril(A,-1) + UniformScaling(1)
U = triu(A)
println("L:\n",L)
println("U:\n",U)
println("LU:\n",L*U)
println("A:\n",A0)

L:
[1.0 0.0; 1.0e17 1.0]
U:
[1.0e-17 1.0; 0.0 -1.0e17]
LU:
[1.0e-17 1.0; 1.0 0.0]
A:
[1.0e-17 1.0; 1.0 3.141592653589793]
