In [1]:
x = 1
typeof(x)

Int64

In [2]:
y = 1.0
typeof(y)

Float64

In [3]:
2*x
2x

2

In [4]:
-3.0 + 2.0*im

-3.0 + 2.0im

In [5]:
π

π = 3.1415926535897...

In [6]:
x = 1
x += 5

6

In [7]:
show(x)

6

In [8]:
x;

In [9]:
show([1 2])

[1 2]

In [10]:
println(x)

6


In [11]:
print("1")
println("2")
println("3")

12
3


In [12]:
using Printf
@printf("The formatting of %5.3f is similar to the C language\n",pi)

The formatting of 3.142 is similar to the C language


In [13]:
using Logging
@info "Everything is going well"
@warn "I can see clouds on the horizon"
@error "The storm is here"

┌ Info: Everything is going well
└ @ Main In[13]:2
┌ Warning: I can see clouds on the horizon
└ @ Main In[13]:3
┌ Error: The storm is here
└ @ Main In[13]:4


In [14]:
using Base.MathConstants

In [15]:
a = [1.0 -1.0 1.0]

1×3 Array{Float64,2}:
 1.0  -1.0  1.0

In [16]:
a = [pi, 2pi, 3pi]

3-element Array{Float64,1}:
 3.141592653589793
 6.283185307179586
 9.42477796076938

In [17]:
show(a)

[3.141592653589793, 6.283185307179586, 9.42477796076938]

In [18]:
@show a

a = [3.141592653589793, 6.283185307179586, 9.42477796076938]


3-element Array{Float64,1}:
 3.141592653589793
 6.283185307179586
 9.42477796076938

In [19]:
@show 1:.1:2
@show LinRange(1,65,17)
@show exp10.(LinRange(1,5,3))

1:0.1:2 = 1.0:0.1:2.0
LinRange(1, 65, 17) = range(1.0, stop=65.0, length=17)
exp10.(LinRange(1, 5, 3)) = [10.0, 1000.0, 100000.0]


3-element Array{Float64,1}:
     10.0
   1000.0
 100000.0

In [20]:
a = [pi -1.0; 2.0 3.0]

2×2 Array{Float64,2}:
 3.14159  -1.0
 2.0       3.0

In [21]:
using LinearAlgebra
@show zeros(2,1)
@show ones(2,3)
@show Diagonal(ones(3,3))

zeros(2, 1) = [0.0; 0.0]
ones(2, 3) = [1.0 1.0 1.0; 1.0 1.0 1.0]
Diagonal(ones(3, 3)) = [1.0 0.0 0.0; 0.0 1.0 0.0; 0.0 0.0 1.0]


3×3 Diagonal{Float64,Array{Float64,1}}:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0

In [22]:
@show UniformScaling(3)

UniformScaling(3) = UniformScaling{Int64}(3)


UniformScaling{Int64}
3*I

In [23]:
@show size( zeros(5,2) )

size(zeros(5, 2)) = (5, 2)


(5, 2)

In [24]:
x = [-1.0 3.0 5.0 pi]
@show x[1] x[2] x[end]

x[1] = -1.0
x[2] = 3.0
x[end] = 3.141592653589793


3.141592653589793

In [25]:
a = [pi -1.0; 2.0 3.0];
@show a[1,2]

a[1, 2] = -1.0


-1.0

In [26]:
a[2,2] = e
@show a

a = [3.141592653589793 -1.0; 2.0 2.718281828459045]


2×2 Array{Float64,2}:
 3.14159  -1.0
 2.0       2.71828

In [27]:
@show a[:,1]
@show a[2,:]

a[:, 1] = [3.141592653589793, 2.0]
a[2, :] = [2.0, 2.718281828459045]


2-element Array{Float64,1}:
 2.0
 2.718281828459045

In [28]:
a = [-1 1]
b = a
@show a
b[1] = 15
@show a

a = [-1 1]
a = [15 1]


1×2 Array{Int64,2}:
 15  1

In [29]:
a = [-1 1]
b = copy(a)
@show a
b[1] = 15
@show a

a = [-1 1]
a = [-1 1]


1×2 Array{Int64,2}:
 -1  1

In [30]:
x = Vector{Float64}(undef,2)
A = Matrix{Float64}(undef,3,2)
@show x, A

(x, A) = ([2.1887342337e-314, 2.238498992e-314], [2.2721655895e-314 2.188731483e-314; 2.268881958e-314 2.165807999e-314; 2.165807991e-314 2.1887315776e-314])


([2.1887342337e-314, 2.238498992e-314], [2.2721655895e-314 2.188731483e-314; 2.268881958e-314 2.165807999e-314; 2.165807991e-314 2.1887315776e-314])

In [31]:
x = fill(0., 2)
A = fill(0., 3, 2)
@show x, A

(x, A) = ([0.0, 0.0], [0.0 0.0; 0.0 0.0; 0.0 0.0])


([0.0, 0.0], [0.0 0.0; 0.0 0.0; 0.0 0.0])

In [32]:
x = [ 1.0 / sqrt(1.0 + i^2) for i=1:4 ]
@show x
A = [ i-j^2 for i=1:4, j=1:2 ]
@show A

x = [0.7071067811865475, 0.4472135954999579, 0.31622776601683794, 0.24253562503633297]
A = [0 -3; 1 -2; 2 -1; 3 0]


4×2 Array{Int64,2}:
 0  -3
 1  -2
 2  -1
 3   0

In [33]:
A = [1 0; -1 1]
x = [1, pi]
A*x

2-element Array{Float64,1}:
 1.0
 2.141592653589793

In [34]:
A = [1 0; 1 1]
x = [1, 0]
A \ x

2-element Array{Float64,1}:
  1.0
 -1.0

In [35]:
x = [1.0 2.0]
@show x.^2
y = [-1.0 5.0]
@show x .+ y
@show x .* y

x .^ 2 = [1.0 4.0]
x .+ y = [0.0 7.0]
x .* y = [-1.0 10.0]


1×2 Array{Float64,2}:
 -1.0  10.0

In [36]:
x = [1.0 2.0]
@show exp.(x)

exp.(x) = [2.718281828459045 7.38905609893065]


1×2 Array{Float64,2}:
 2.71828  7.38906

In [37]:
A = [0 1 2; 3 4 0; 0 5 6]
@show A
@show opnorm(A,1)
@show opnorm(A,2)
@show opnorm(A,Inf)

A = [0 1 2; 3 4 0; 0 5 6]
opnorm(A, 1) = 10.0
opnorm(A, 2) = 8.612425896637122
opnorm(A, Inf) = 11.0


11.0

In [38]:
@show norm(A)

norm(A) = 9.539392014169456


9.539392014169456

In [39]:
A = [1 0 0 1; -1 1 0 1; -1 -1 1 1; -1 -1 -1 1]
F = lu(A)
@show F.L
@show F.U
@show F.p

F.L = [1.0 0.0 0.0 0.0; -1.0 1.0 0.0 0.0; -1.0 -1.0 1.0 0.0; -1.0 -1.0 -1.0 1.0]
F.U = [1.0 0.0 0.0 1.0; 0.0 1.0 0.0 2.0; 0.0 0.0 1.0 4.0; 0.0 0.0 0.0 8.0]
F.p = [1, 2, 3, 4]


4-element Array{Int64,1}:
 1
 2
 3
 4

In [40]:
A[F.p,:] == F.L*F.U ? "SUCCESS" : "FAIL"

"SUCCESS"

In [41]:
t = pi / 4
A = [cos(t) sin(t); -sin(t) cos(t)] * [1 -1; 0 1/8]
F = qr(A)
@show F.Q
@show F.R

F.Q = [-0.7071067811865475 0.7071067811865475; 0.7071067811865475 0.7071067811865476]
F.R = [-1.0 1.0; 0.0 0.125]


2×2 Array{Float64,2}:
 -1.0  1.0
  0.0  0.125

In [42]:
A = [0 1 0; 0 0 1; 1 0 0]
F = eigen(A)
@show F.values
@show F.vectors

F.values = Complex{Float64}[-0.5 - 0.8660254037844389im, -0.5 + 0.8660254037844389im, 0.9999999999999998 + 0.0im]
F.vectors = Complex{Float64}[0.577350269189626 - 0.0im 0.577350269189626 + 0.0im -0.5773502691896256 + 0.0im; -0.28867513459481303 - 0.4999999999999997im -0.28867513459481303 + 0.4999999999999997im -0.5773502691896256 + 0.0im; -0.28867513459481287 + 0.4999999999999999im -0.28867513459481287 - 0.4999999999999999im -0.577350269189626 + 0.0im]


3×3 Array{Complex{Float64},2}:
   0.57735-0.0im    0.57735+0.0im  -0.57735+0.0im
 -0.288675-0.5im  -0.288675+0.5im  -0.57735+0.0im
 -0.288675+0.5im  -0.288675-0.5im  -0.57735+0.0im

In [43]:
A = [0 1 0; 0 0 1; 1 0 0]
F = schur(A)
@show F.Schur
@show F.vectors

F.Schur = [-0.5 0.8660254037844394 2.093866863762892e-16; -0.8660254037844386 -0.5 3.414324379582377e-16; 0.0 0.0 0.9999999999999998]
F.vectors = [0.8038980964653946 -0.14287937977882714 -0.5773502691896257; -0.27821187566726857 0.7676358634823983 -0.5773502691896256; -0.5256862207981258 -0.6247564837035714 -0.5773502691896257]


3×3 Array{Float64,2}:
  0.803898  -0.142879  -0.57735
 -0.278212   0.767636  -0.57735
 -0.525686  -0.624756  -0.57735

In [44]:
A = [1 2 3; 3 1 2; 2 3 1]
F = svd(A)
@show F.U
@show F.S
@show F.V

F.U = [-0.5773502691896258 0.7071067811865477 -0.40824829046386313; -0.577350269189626 -0.7071067811865476 -0.408248290463863; -0.5773502691896258 1.1102230246251565e-16 0.816496580927726]
F.S = [5.999999999999999, 1.7320508075688776, 1.7320508075688772]
F.V = [-0.5773502691896257 -0.816496580927726 -0.0; -0.5773502691896257 0.4082482904638629 0.7071067811865475; -0.5773502691896257 0.40824829046386296 -0.7071067811865476]


3×3 Adjoint{Float64,Array{Float64,2}}:
 -0.57735  -0.816497  -0.0
 -0.57735   0.408248   0.707107
 -0.57735   0.408248  -0.707107

In [45]:
s = 0.0
for i=1:10
    s += 1.0 / i
end
@show s

s = 2.9289682539682538


2.9289682539682538

In [46]:
s = 0.0
for i = 1:2:9
    s += 1.0 / i
end
@show s

s = 1.7873015873015872


1.7873015873015872

In [47]:
s = 0.0
for i = exp2.(0:2:8)
    s += 1.0 / i
end
@show exp2.(0:2:8)

exp2.(0:2:8) = [1.0, 4.0, 16.0, 64.0, 256.0]


5-element Array{Float64,1}:
   1.0
   4.0
  16.0
  64.0
 256.0

In [48]:
# Another way of doing the same thing
s = 0.0
for i = 2 .^(0:2:8)
    s += 1.0 / i
end
@show 2 .^(0:2:8)

2 .^ (0:2:8) = [1, 4, 16, 64, 256]


5-element Array{Int64,1}:
   1
   4
  16
  64
 256

In [49]:
s = 0.0
for i = [1 4 16]
    s += 1.0 / i
end
s

1.3125

In [50]:
x = 1.0; f = 1.0; i = 2
while f > eps(1.0)
    x += f
    f /= i
    i += 1
end
@show x, e

(x, e) = (2.7182818284590455, ℯ)


(2.7182818284590455, ℯ)

In [51]:
function flog(n,x)
    p = -x
    l = 0.0
    for i=1:n
        l += p/i
        p *= x
    end
    return l
end
@show flog(20,0.5), log(1-0.5)

(flog(20, 0.5), log(1 - 0.5)) = (-0.6931471370510288, -0.6931471805599453)


(-0.6931471370510288, -0.6931471805599453)

In [52]:
fpower(x,y) = x^y
@show fpower(2,3)

fpower(2, 3) = 8


8

In [53]:
map(x -> x^2 + 2x + 1, 1:4)

4-element Array{Int64,1}:
  4
  9
 16
 25

In [54]:
function f_reference(x,y)
    x += 1
    y[1] += 1
    return x
end
x = 1
y = [-4 3]
@show x,y
@show f_reference(x,y)
@show x,y

(x, y) = (1, [-4 3])
f_reference(x, y) = 2
(x, y) = (1, [-3 3])


(1, [-3 3])

In [55]:
tup = (pi,e)
tup[1]

π = 3.1415926535897...

In [56]:
function f_multiple(x)
    return (x, 2x, 4x)
end
f_multiple(3)

(3, 6, 12)

In [57]:
x, y = golden, eulergamma
@show x, y

(x, y) = (φ, γ)


(φ, γ)

In [58]:
f_multiple.([1, 2])

2-element Array{Tuple{Int64,Int64,Int64},1}:
 (1, 2, 4)
 (2, 4, 8)

In [59]:
function f_type(x::UInt32) # 32 bit unsigned integer
    return x + 3
end
@show f_type(UInt32(1))
#f_type(UInt32(-1)) # Conversion error
#f_type(1)          # Wrong type for input variable; 1 is an Int64

f_type(UInt32(1)) = 4


4

In [60]:
function f_if_then_else(x)
    if x > 0
        return log(x)
    elseif x < 0
        @warn "The input argument is negative; returning log(-x)"
        return log(-x)
    else
        @error "The input argument is equal to 0"
    end
end
@show f_if_then_else(2)
@show f_if_then_else(-2)
@show f_if_then_else(0)

f_if_then_else(2) = 0.6931471805599453
f_if_then_else(-2) = 0.6931471805599453
f_if_then_else(0) = nothing


┌ Warning: The input argument is negative; returning log(-x)
└ @ Main In[60]:5
┌ Error: The input argument is equal to 0
└ @ Main In[60]:8
