In [1]:
n = 100
println("Size of matrix ", n)

# Initialize the random number generator
using Random
rng = MersenneTwister(2016)

Size of matrix 100


MersenneTwister(UInt32[0x000007e0], Random.DSFMT.DSFMT_state(Int32[279760899, 1073504215, 1972863571, 1072951865, -1288004177, 1073580911, 1922397108, 1073368074, 1873668020, 1072728877  …  -307315196, 1073391349, 1779087006, 1073380154, -1070889124, -1099062091, 1944769775, 1287223881, 382, 0]), [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], UInt128[0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000  …  0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000

In [2]:
# Initialize the matrix
using LinearAlgebra
Qe, Re = qr(rand(n,n))
# Qe is orthogonal, Re is upper triangular
for i=1:n
    # Multiply row i by 1/2^i
    Re[i,:] /= 2.0^(i/3.2)
end

# A = Qe * Re
A = Qe * Re

100×100 Array{Float64,2}:
 0.564246     0.332117   0.458735   …  0.370224  0.443338  0.393896
 0.000807811  0.520631   0.427097      0.452255  0.393754  0.385226
 0.544118     0.279929   0.556136      0.380208  0.495185  0.422274
 0.506381     0.298715   0.392655      0.284728  0.363863  0.363293
 0.149543     0.579259   0.60568       0.408941  0.367376  0.442297
 0.124372     0.520497   0.354944   …  0.401609  0.36454   0.404229
 0.60765      0.154787   0.310366      0.277868  0.35619   0.292771
 0.0569296    0.0381162  0.0221815     0.146069  0.152613  0.127181
 0.16455      0.147546   0.452999      0.256002  0.286871  0.278856
 0.298842     0.267725   0.373328      0.285864  0.315465  0.311499
 0.75753      0.13511    0.56459    …  0.270892  0.397493  0.37991
 0.534413     0.567716   0.354931      0.413058  0.443519  0.452642
 0.733215     0.45288    0.648814      0.394326  0.452893  0.523217
 ⋮                                  ⋱                      
 0.657325     0.630413   0.4717

In [3]:
# Compute QR factorization of A
Q, R = qr(A)

# Fix possible differences in the sign of the diagonal entries of R
for i=1:n
    if R[i,i] * Re[i,i] < 0
        R[i,:] = -R[i,:]
        Q[:,i] = -Q[:,i]
    end
end

# We now expect that Q=Qe and R=Re.

In [4]:
# Calculate the error in Q
e = zeros(n)
for j=1:n
    # Processing column j
    e[j] = norm(Q[:,j] - Qe[:,j])
end

In [5]:
Q[end-2:end,end-2:end]

3×3 Array{Float64,2}:
 -0.143942   -0.0814032  0.0585257
 -0.0911133  -0.0391646  0.0202537
  0.0494305  -0.0635674  0.0666691

In [6]:
Qe[end-2:end,end-2:end]

3×3 Array{Float64,2}:
 -0.143942   -0.0814034  0.0585253
 -0.0911135  -0.0391648  0.0202533
  0.0494304  -0.0635673  0.0666693

In [7]:
using Plots
plotlyjs()

HTML{String}("<script>\n// Immediately-invoked-function-expression to avoid global variables.\n(function() {\n    var warning_div = document.getElementById(\"webio-warning-5569494847372921863\");\n    var hide = function () {\n        var script = document.getElementById(\"webio-setup-1329126803716019344\");\n        var parent = script && script.parentElement;\n        var grandparent = parent && parent.parentElement;\n        if (grandparent) {\n            grandparent.style.display = \"none\";\n        }\n        warning_div.style.display = \"none\";\n    };\n    if (typeof Jupyter !== \"undefined\") {\n        console.log(\"WebIO detected Jupyter notebook environment.\");\n        // Jupyter notebook.\n        var extensions = (\n            Jupyter\n            && Jupyter.notebook.config.data\n            && Jupyter.notebook.config.data.load_extensions\n        );\n        if (extensions && extensions[\"webio-jupyter-notebook\"]) {\n            // Extension already loaded.\n            console.log(\"Jupyter WebIO nbextension detected; not loading ad-hoc.\");\n            hide();\n            return;\n        }\n    } else if (window.location.pathname.includes(\"/lab\")) {\n        // Guessing JupyterLa\n        console.log(\"Jupyter Lab detected; make sure the @webio/jupyter-lab-provider labextension is installed.\");\n        hide();\n        return;\n    }\n})();\n\n</script>\n<p\n    id=\"webio-warning-5569494847372921863\"\n    class=\"output_text output_stderr\"\n    style=\"padding: 1em; font-weight: bold;\"\n>\n    Unable to load WebIO. Please make sure WebIO works for your Jupyter client.\n    For troubleshooting, please see <a href=\"https://juliagizmos.github.io/WebIO.jl/latest/providers/ijulia/\">\n    the WebIO/IJulia documentation</a>.\n    <!-- TODO: link to installation docs. -->\n</p>\n")

Plots.PlotlyJSBackend()

In [8]:
# Re-run all cells to get the plot below
using Plots.PlotMeasures
plot(e, lab="Error in R[i,i]", yscale = :log10, xlabel="Column index", ylabel="Error", left_margin = 50px)

<!DOCTYPE html>
 
 
 Plots.jl

In [9]:
using HDF5
h5open("QR_hwk_matrix_data.h5", "w") do file
    write(file,"matrix_A", A)
end

In [10]:
A0 = h5read("QR_hwk_matrix_data.h5", "matrix_A")
@show norm(A - A0)

norm(A - A0) = 0.0


0.0